# Language
language:
  - python
# Supported version
python:
  - 3.6
# Install dependecies
install:
  - pip install -r requirements.txt
# Database service
services:
  - postgresql
# Database setup
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'create database flask_api;' -U postgres
# Test Script
script:
 py.test --cov=app tests/
 
# Coveralls reporting
after_success:
  - coveralls