"""empty message

Revision ID: b04574dee080
Revises: 7dadcb6db462
Create Date: 2018-01-08 07:20:38.812814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04574dee080'
down_revision = '7dadcb6db462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'created_by')
    # ### end Alembic commands ###
